image: docker:latest
services:
  - docker:dind

stages:
  - before_script

clone:
  stage: before_script
  script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && ssh-keyscan -H "156.67.214.146" > ~/.ssh/known_hosts'
