image: docker:latest
services: docker:dind

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && ssh-keyscan -H "156.67.214.146" > ~/.ssh/known_hosts'

deploy_staging:
  type: deploy
  script:
    - ssh root@156.67.214.146 "cd /var/www/ && rm -rf upja && git checkout master && git pull origin master && exit"
  only:
    - master
